POST http://localhost:3001/api/products/add?dataTab=size&productId=5f320ed808a26c4890e3246f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYxZDg1OGY5ZmMzMDQzZTA0NjMxMzg2IiwidXNlcm5hbWUiOiJBZG1pbiJ9LCJpYXQiOjE1OTcxNjkzNDJ9.jCmI3SWqsvqkqenZ3mn7B1XIgMoHRVtpffpk7UilNkM

{
  "storeId":"5f31b1fc601dcd16cc5d49c5",
  "varientId":"5f3211b508a26c4890e32476",
  "sizeId":"5f21ac9552f5b95718f975df",
  "allQuantity":"100"
}
