POST http://localhost:3001/api/products/delete?dataTab=varient&productId=5f320ed808a26c4890e3246f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYxZDg1OGY5ZmMzMDQzZTA0NjMxMzg2IiwidXNlcm5hbWUiOiJBZG1pbiJ9LCJpYXQiOjE1OTcxNjkzNDJ9.jCmI3SWqsvqkqenZ3mn7B1XIgMoHRVtpffpk7UilNkM

{
  "storeId":"5f32e6c340413f47f4a85c30",
  "varientId":"5f320ed808a26c4890e32470"
}
