POST http://localhost:3001/api/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYxZDg1OGY5ZmMzMDQzZTA0NjMxMzg2IiwidXNlcm5hbWUiOiJBZG1pbiJ9LCJpYXQiOjE1OTcxMDAwOTV9.YjK4gM4WPJPk81Q2T8pdEkffKjLJD8IcEpxy7XuJg-c

{
  "name":"gdkjgfidjg",
  "sku":"a15205",
  "storeId":"5f31d0f7cfd5642e8828c961",
  "classId":"5f31d11ecfd5642e8828c962",
  "varId":"5f31d1bc43311221a466e36a",
  "buyPrice":"50",
  "sellPrice":"500",
  "productColors":[
      {
          "colorId":"5f1ae664ab6bfc2de8a06a69",
          "image":"https://aiimagestrain.storage.googleapis.com/0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg",
          "filename":"0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg",
          "colorSizes":[
              {
                "sizeId":"5f1f6e54dc1d022084365cfe",
                "allQuantity":"50",
                "quantityNow":"50"
              },
              {
                "sizeId":"5f206007e5ef934bc0826e78",
                "allQuantity":"30",
                "quantityNow":"30"
              }
          ]
      },
      {
          "colorId":"5f1f6d5166aa572e1875361d",
          "image":"https://aiimagestrain.storage.googleapis.com/0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg",
          "filename":"0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg",
          "colorSizes":[
              {
                "sizeId":"5f1f6e54dc1d022084365cfe",
                "allQuantity":"20",
                "quantityNow":"20"
              },
              {
                "sizeId":"5f206007e5ef934bc0826e78",
                "allQuantity":"80",
                "quantityNow":"80"
              }
          ]
      }
  ]
}
