POST http://localhost:3001/api/products/update?dataTab=varient&productId=5f31ce126135e168f8f9c08c
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYxZDg1OGY5ZmMzMDQzZTA0NjMxMzg2IiwidXNlcm5hbWUiOiJBZG1pbiJ9LCJpYXQiOjE1OTcxNjkzNDJ9.jCmI3SWqsvqkqenZ3mn7B1XIgMoHRVtpffpk7UilNkM

{
  "storeId":"5f32e6c340413f47f4a85c30",
  "colorId":"5f21ebbeb46e045778f3806f",
  "image":"https://aiimagestrain.storage.googleapis.com/0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg",
  "filename":"0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg"
}
