POST http://localhost:3001/api/products/update?dataTab=varient&productId=5f31ce126135e168f8f9c08c
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYzMWFmM2M0ZWNlOWEzNDg0YjAwMjZhIiwidXNlcm5hbWUiOiJtYWhtb3VkIn0sImlhdCI6MTU5NzA5MzkwOH0.4BqPCadLjydwYl4vfMP_JKJJglKl0ALhsCXdXBWou0s

{
  "storeId":"5f31b1fc601dcd16cc5d49c5",
  "colorId":"5f21ebbeb46e045778f3806f",
  "image":"https://aiimagestrain.storage.googleapis.com/0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg",
  "filename":"0c9e3400-d8bb-11ea-9cb7-939416916fd6_4.jpg"
}
