POST http://localhost:3001/api/products/update?dataTab=quantity&productId=5f2ef401166f17377c560780
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYTFjYTAxNDk0NGI1OWYwY2I0NmJmIiwidXNlcm5hbWUiOiJtb2hhbWVkIGh1c3NhbSJ9LCJpYXQiOjE1OTY2NzU2MTh9.ZaAZ65EWpX1nsO2XcD0YEXxAyMKHQAuI0xuC01c6h-A

{
  "varientId":"5f2ef401166f17377c560781",
  "sizeQuantityId":"5f2ef401166f17377c560782",
  "sizeId":"5f21ac9552f5b95718f975df",
  "allQuantity":"100"
}
