POST http://localhost:3001/api/products/update?dataTab=regular&productId=5f321b263cfcb026ec6e5d10
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYxZDg1OGY5ZmMzMDQzZTA0NjMxMzg2IiwidXNlcm5hbWUiOiJBZG1pbiJ9LCJpYXQiOjE1OTcxNjkzNDJ9.jCmI3SWqsvqkqenZ3mn7B1XIgMoHRVtpffpk7UilNkM

{
  "storeId":"5f32e6c340413f47f4a85c30",
  "name":"habzlm",
  "sku":"12356",
  "buyPrice":"50",
  "sellPrice":"500",
  "classId":"5f1ff69a19758b5c3c2c521d",
  "varId":"5f21ec38b46e045778f38072"
}
